#!/bin/sh -xe

script/bootstrap

rm -rf coverage/

bin/rake "spec:appraisal:rails3.0.x spec:unit"
bin/rake "spec:appraisal:rails3.1.x spec:unit"
bin/rake "spec:appraisal:rails3.2.x spec:unit"
bin/rake "spec:appraisal:rails4.0.x spec:unit" COVERAGE=true
bin/rake "spec:quality"
